time: 60
drop: STICK
allow-refueling: true
refuel-type: RESET
sound-on-fuel: true
particle-on-fuel: true
hologram-on-fuel: true
refuel-items:
  - COAL
  - CHARCOAL
burnout-in-creative: false
autosave: false
autosave-frequency: 600
reload_message: '&a&lRELOADED! &aBurnoutTorches config reloaded!'
bad_arguments_message: '&c&lBAD ARGS! &cIncorrect arguments! Usage: /bt reload'
no_permission_message: '&c&lNO PERMISSION! &cYou do not have permission to perform
  this command!'
